---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: op-rolebinding-default
  namespace: allowed-one
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scoped-memcached-operator-manager-role
subjects:
- kind: ServiceAccount
  name: scoped-memcached-operator-controller-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: op-rolebinding-default
  namespace: allowed-two
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scoped-memcached-operator-manager-role
subjects:
- kind: ServiceAccount
  name: scoped-memcached-operator-controller-manager
  namespace: default
