apiVersion: cache.example.com/v1alpha1
kind: Memcached
metadata:
  name: memcached-sample-allowed-one
  namespace: allowed-one
spec:
  size: 2
---
apiVersion: cache.example.com/v1alpha1
kind: Memcached
metadata:
  name: memcached-sample-allowed-two
  namespace: allowed-two
spec:
  size: 3
# ---
# apiVersion: cache.example.com/v1alpha1
# kind: Memcached
# metadata:
#   name: memcached-sample-denied
#   namespace: denied
# spec:
#   size: 1